export default {
  class: 'className',
  for: 'htmlFor',
  maxlength: 'maxLength',
  colspan: 'colSpan',
  rowspan: 'rowSpan',
  tabindex: 'tabIndex',
  readonly: 'readOnly',
  enctype: 'encType',
  novalidate: 'noValidate',
  autoplay: 'autoPlay',
  srcset: 'srcSet',
  contenteditable: 'contentEditable',
  formnovalidate: 'formNoValidate',
  referrerpolicy: 'referrerPolicy',
  allowfullscreen: 'allowFullScreen',
  spellcheck: 'spellCheck',
  autofocus: 'autoFocus',
  frameborder: 'frameBorder',
  usemap: 'useMap',
  acceptcharset: 'acceptCharset',
  crossorigin: 'crossOrigin',
  mediagroup: 'mediaGroup',
  marginwidth: 'marginWidth',
  marginheight: 'marginHeight',
  inputmode: 'inputMode',
} as Record<string, string>;
